### ISSUE TITLE
Doesn't upload files created/modified outside of Atom.

### ISSUE THREAD

**Issue by AaronV** [SqrTT/Bart#11]
I have a grunt process that compiles my scss files into css, but Bart doesn't upload those.

It also doesn't upload files added when outside of Atom.

**Comment by SqrTT** [comment]
Hi @AaronV 
You may specify file or files list in plugin config which should be watched:

![](http://apps.sqrtt.pro/screenshots/Selection_00111%3A27%3A14.png)

You can use masks for files like `*` or `?` (glob format is used)

**Comment by AaronV** [comment]
Thanks for the help, but I wasn't able to get this working for me.

I have files uploading/updating correctly when saved from within Atom. However if I create a file or add one to a directory outside of Atom, it isn't recognized and uploaded.

If I open that new file in Atom, and save it, then it uploads.

I'm not sure how to get Bart watching files that aren't modified inside Atom.

PS: There is a typo in the line of text "List of cartrigges that should be uploaded..." Should be "cartridges".

**Comment by SqrTT** [comment]
Bart, doesn't watch all files by default, but has config where could be specified files that should be watched.

Closing as outdated.
