### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by haan123** [SqrTT/Bart#20]
I have met this error when trying to upload file to sand box, all config for my sand box are correct.

This is the log: 
`
Uncaught (in promise) Error: Notification must be created with string message: Error: Internal Server Error(…)
module.exports.Notification.validate @ notification.coffee:17
Notification @ notification.coffee:13
module.exports.NotificationManager.addError @ notification-manager.coffee:132
(anonymous function) @ /home/an/.atom/packages/Bart/lib/bart.js:267
_tickCallback @ internal/process/next_tick.js:103
`

**Comment by ranveer5289** [comment]
Hello,

Two things come to my mind right-away:

1.  Are you using the latest version of the package?
2. Can you please paste the screenshot of your project structure in Atom. Please refer issue https://github.com/SqrTT/Bart/issues/8 . As I understand Bart plugin needs a specific project structure in order to upload files to DWRE sandbox.

Thanks

**Comment by haan123** [comment]
Hi @ranveer5289

Sorry for my late response, i don't know why i didn't get any notification of your reply.
1. I'm using 1.4.0
2. My current project is built on new controller approach, all third party cartridge are installed by `npm install` and placed in `node_modules` folder

This is my project tree:
![project_tree](https://cloud.githubusercontent.com/assets/5218341/21375341/6d1a77d8-c75f-11e6-995c-e74094ac97ae.png)

**Comment by ranveer5289** [comment]
Hey,

I can see your root folder in atom project is `surfstitch-demandware`. So, your project hierarchy in atom becomes  `surfstitch-demandware >> client >> cartridges`

Can you make `client` as the root of your atom project by selctecing `client` folder when adding new project in atom . So, that your project hierarchy becomes  in atom ` client >> cartridges`.

Let's see if that solves your issue.

**Comment by haan123** [comment]
Thanks a lot for your support @ranveer5289 :+1: , i think your solution will work properly, but i need to navigate to other cartridges those are in `node_modules` and i have resolved my problem by added this `client/surfstitch_storefront_core` path to the **list of cartidge should be uploaded**

**Comment by ranveer5289** [comment]
@haan123 So, can we close this issue ?

**Comment by haan123** [comment]
Please close it, @ranveer5289, thanks! :)
