### ISSUE TITLE
Deprecated selector in `Bart/styles/bart.less`

### ISSUE THREAD

**Issue by matteobertoldo** [SqrTT/Bart#21]
In `Bart/styles/bart.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .gutter .line-number.bart-stop-line:before` => `atom-text-editor.editor .gutter .line-number.bart-stop-line:before`

* `atom-text-editor::shadow .gutter .line-number.node-debugger-attached-breakpoint` => `atom-text-editor.editor .gutter .line-number.node-debugger-attached-breakpoint`

* `atom-text-editor::shadow .gutter .line-number.bart-breakpoint` => `atom-text-editor.editor .gutter .line-number.bart-breakpoint`

* `atom-text-editor::shadow .bart-breakpoint_active` => `atom-text-editor.editor .bart-breakpoint_active`

**Comment by SqrTT** [comment]
thanks for bringing this up

**Comment by SqrTT** [comment]
fixed in v1.6.0
