### ISSUE TITLE
Uncaught TypeError: Bart.progressMsg.clear is not a function

### ISSUE THREAD

**Issue by jcassanyjcs** [SqrTT/Bart#25]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [Bart](https://github.com/SqrTT/bart) package 1.7.0

### Stack Trace

Uncaught TypeError: Bart.progressMsg.clear is not a function

```
At /Users/josecassany/.atom/packages/Bart/lib/bart.js:353

TypeError: Bart.progressMsg.clear is not a function
    at Object.uploadAll (/packages/Bart/lib/bart.js:353:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -1:04.4.0 bart:uploadAll (div.panels-item)
```

### Non-Core Packages

```
Bart 1.7.0 
```

**Comment by SqrTT** [comment]
Could you please install [busy-signal](https://atom.io/packages/busy-signal)?

I thought that atom takes care about dependency automatically...

**Comment by SqrTT** [comment]
Sorry for introducing instability...

**Comment by jcassanyjcs** [comment]
Thank you. I installed busy signal. I don't see any errors now. But it doesn't seem to be working correctly. Auto upload is not working correctly. Let me do some more testing.

**Comment by jcassanyjcs** [comment]
Nope. Even with busy signal installed I couldn't send the new zip to my remote. It gets stuck in "sending zip to remote" forever. I have another machine with the old version of Bart and works like a charm. No need to apologize LOL I've been using Bart for a long time now and it is great to have an option to work out of eclipse. Question... have you tested this new version on your machine?

**Comment by SqrTT** [comment]
Thanks for patient. 

Yes, I've tested and upload all forks for me... but looks I've missed something.

Is your directory structure something like this?

![img](https://cloud.githubusercontent.com/assets/1271300/15393102/1b56c7ce-1dd4-11e6-87e0-4c3c3a15ef66.png)

**Comment by jcassanyjcs** [comment]
Yes, my directory looks very similar, just plain catridges. Also use source tree for branching. As of right now I went back to the old version of Bart and works as intended. Thanks for working on this.

**Comment by SqrTT** [comment]
Hi @jcassanyjcs. I've released new version 1.8.0 where changed all a watching logic and upload all cartridges. Could you please verify if it solve this issue?

**Comment by jcassanyjcs** [comment]
@SqrTTT Thank you! this version works. Was able to upload all cartridges correctly and all errors are gone.

**Comment by SqrTT** [comment]
Thank you for a reporting and testing. Feel free to report any weird things that you notice.
