### ISSUE TITLE
Bart doesn't open anymore to edit settings

### ISSUE THREAD

**Issue by Pepo** [SqrTT/Bart#31]
Hey SqrTT,

thanks a lot for your amazing work. It helps me a lot.
In 1.21.1 i can't open the Menu anymore 
![bildschirmfoto 2017-10-23 um 13 22 01](https://user-images.githubusercontent.com/521436/31886844-4ec145a4-b7f6-11e7-85be-81fa9704a1e6.png)

I've reinstalled atom but nothing happens. The Open-settings menu will not open.

What can i do? 

Many greets from Berlin,
Pepo

**Comment by SqrTT** [comment]
Hi @Pepo 
Thanks for reporting.
 Unfortunately, I don't have time to maintain this extension. So basically you have next options:
* Manually edit `dw.json`
* Switch to [VS Code](https://code.visualstudio.com/) and [Prophet](https://marketplace.visualstudio.com/items?itemName=SqrTT.prophet) extension (recommended)
* try to figure out whats wrong and try to fix the issue.


Regards

**Comment by Pepo** [comment]
I forgot to say thank you. I am happy with my personal switch to VS Code.

Thank you, for your great work on that thing!

XOXO ;-)
