### ISSUE TITLE
Setting breakpoints in debugger fails on Windows

### ISSUE THREAD

**Issue by jkol** [SqrTT/Bart#4]
On Windows, creating a breakpoint sends the following request to the API:
`{"breakpoints":[{"line_number":88,"script_path":"\\app_storefront_core\\cartridge\\scripts\\filename.ds"}]}`

The debugger is responding with this error:
`{"_v":"1.0","fault":{"type":"InvalidScriptPathException","message":"Script Path must start with a forward slash '/'."}}`

**Comment by SqrTT** [comment]
Hi, thanks for feedback, I'll take a look on that.

**Comment by SqrTT** [comment]
Hi @jkol 
Could you verify if this occurs in 1.2.2 version, please?

**Comment by jkol** [comment]
This appears to be resolved. Thank you!
