### ISSUE TITLE
Use `dw.json` instead for options

### ISSUE THREAD

**Issue by tnguyen14** [SqrTT/Bart#7]
Instead of having local options stored in Atom, could this support the use of `dw.json`, which is a file that would contain the same information (`hostname`, `username` and `password`). This way, each project (or directory for that matter) could have its own configuration?

**Comment by SqrTT** [comment]
This is good idea, I'll take a look how it can be done.

**Comment by SqrTT** [comment]
Implemented by @AlexTask in https://github.com/SqrTT/Bart/pull/18

**Comment by jkol** [comment]
Any chance we could get a new release pushed to the atom repos with this change added?

**Comment by SqrTT** [comment]
Done
