### ISSUE TITLE
Code Upload Doesn't work on OSX

### ISSUE THREAD

**Issue by ranveer5289** [SqrTT/Bart#8]
On OSX when I try to upload file I get below error 

`Uncaught (in promise) Error: Notification must be created with string message: Error: Internal Server Error(…)module.exports.Notification.validate @ /Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25Notification @ /Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:20module.exports.NotificationManager.addError @ /Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:41(anonymous function) @ bart.js:228_tickCallback @ node.js:392`

<img width="883" alt="screen shot 2016-05-18 at 22 07 29" src="https://cloud.githubusercontent.com/assets/826004/15373251/0334db34-1d45-11e6-9393-ec2994f66302.png">

I am using latest version of Bart & I installed it using `apm install bart`. 

When I enter all my details in `Open Settings` dialog, I don't get any error. I guess it got authenticated successfully.

My project structure is as follow. I have directly added the cartridge in atom workspace.

<img width="193" alt="screen shot 2016-05-18 at 22 06 14" src="https://cloud.githubusercontent.com/assets/826004/15373222/cd386212-1d44-11e6-8682-842107d93a0a.png">

**Comment by SqrTT** [comment]
Hi @ranveer5289 thanks for reporting this.

Honestly I didn't expect that each cartridge will be added as project (as it was in eclipse).

Expected stricture is open folder that contain needed cartridges. Example:
![screenshot from2016-05-19144535](https://cloud.githubusercontent.com/assets/1271300/15393102/1b56c7ce-1dd4-11e6-87e0-4c3c3a15ef66.png)

And if you don't need all of them just specify cartridges in config: 
![screenshot from 2016-05-19 144625](https://cloud.githubusercontent.com/assets/1271300/15393112/211366a4-1dd4-11e6-8a16-f62258c8aee6.png)

Could you try this structure, please? Of course if it fits to you and I will try figure out how can be implemented structure: one project - one cartridge

Thanks

**Comment by ranveer5289** [comment]
Thanks for the reply. Yes, suggested structure works form me :)

I guess we can also close issue  #1 as authentication works fine on OSX.

My OSX version details:

<img width="587" alt="screen shot 2016-05-19 at 15 03 03" src="https://cloud.githubusercontent.com/assets/826004/15394356/d1217e20-1dd2-11e6-9819-bc7b01f1d6c0.png">
